---

- name: apache configure   
  yum: name="{{ item }}" state=present
  with_items:
  - httpd
  - httpd-devel
  - mod_ssl
  tags:
  - install

- name: Ensure httpd is running
  service: name=httpd state=started enabled=yes

- name: Set SELinux httpd net connection
  command: sudo /usr/sbin/setsebool httpd_can_network_connect 1

- include: config_php.yml tags=php

#  Configure virtual host 


